version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: libreria-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: libreria-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge
    internal: true